### PR TITLE
part6a suggestions

### PR DESCRIPTION
**Pull request by I-keep-trying**
I did my best to pinpoint where I got confused, and tried to add some clarification that only came *after* I eventually got my local notes app to match what was supposed to be happening according to the instructions. I added a section before the deep-freeze test is created, where it seemed like you should already have the 'noteReducer.js' file already created, but if you want that after, that could work too. 

My changes have been marked with <mark> tags or commented  in places where <mark> doesn't work (inside code blocks). I did my best to indicate where sections were moved from/to as well. Those markings will have to be deleted first if this is merged, obviously. Let me know you you want me to do that, or any other edits.

### CODE REVIEW

**Comment by sahilrajput03** [comment]
What linter did you use, seems like the additions you made had made the original lintings of the course's content distorted, look yourself, I hope you are aware of this https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/pull/700/commits/303d8973efc1702b41d4f0726356e484bf5e61f1. 

Changing/altering the schema of document doesn't make a good pr, I strongly suggest you to make new pr with no linters enabled, so changes could be easily differentiated, right now its very difficult to analyse differences, because there's lots  of tabs, commas, extra lines, etc linting additions/subtractions. 
Do see it here. 
https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/pull/700/commits/303d8973efc1702b41d4f0726356e484bf5e61f1
Thanks, 
I'm not admin/official contributor of this project, but just told you all that for sake of making a good pr. Thanks, never mind, if that doens't help.

**Comment by I-keep-trying** [comment]
> What linter did you use, seems like the additions you made had made the original lintings of the course's content distorted, look yourself, I hope you are aware of this [303d897](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/commit/303d8973efc1702b41d4f0726356e484bf5e61f1).
> 
> Changing/altering the schema of document doesn't make a good pr, I strongly suggest you to make new pr with no linters enabled, so changes could be easily differentiated, right now its very difficult to analyse differences, because there's lots of tabs, commas, extra lines, etc linting additions/subtractions.
> Do see it here.
> [303d897](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/commit/303d8973efc1702b41d4f0726356e484bf5e61f1)
> Thanks,
> I'm not admin/official contributor of this project, but just told you all that for sake of making a good pr. Thanks, never mind, if that doens't help.

Hey sorry I just now saw this. 

I appreciate the feedback! I have never done a PR at all, period. This is my very first one. I had a feeling I might (probably) be doing something wrong, so, I do appreciate the info. 

I will take a look at some others and see what I need to fix. 

Thanks!

**Comment by sahilrajput03** [comment]
Sure, yeah github has poor notifications system as I feel, it happens with me all the time. And its really fun to do these pr's. :)

**Comment by sahilrajput03** [comment]
I suggest you see some **merged** pr, and see the **Files Changed** section in those PR's as you see what are additions(green) and subtractions(red).

**Comment by jayeshmann** [comment]
@I-keep-trying Make _subtle_ and _multiple_ commits

**Comment by I-keep-trying** [comment]
Can we just close this pr and I'll make a new one?

**Comment by jayeshmann** [comment]
@Kaltsoon Author is requesting this PR to be closed.

**Pull request closed without merging**
