### PR TITLE
Hosting the site at a path other than the root of the domain

### PR DESCRIPTION
**Pull request by blelem**
It is currently not possible to host the fullstack-hy2020 site at a path other than the root of the domain: the path of the images used in the markdown pages are not correctly prefixed.

For example, if I would like to host the site at: 
`example.github.io/fullstack-hy2020/`

I would follow the procedure described at https://www.gatsbyjs.com/docs/path-prefix/, that is: 

- add the **fullstack-hy2020** pathPrefix value to my gatsby-config.js.
- build my site with `gatsby build --prefix-paths`

Gatsby does add the pathPrefix to all paths on the site, with the exception of the images used in the markdown pages. The pathPrefix is not added to those images. Consequently, when rendering a page of the site at the url `http://example.github.io/fullstack-hy2020/osa1/reactin_alkeet/` the browser looks for the images under the url `http://example.github.io/static/` instead of `http://example.github.io/fullstack-hy2020/static/` and therefore fails to load them.

To correct the situation, I retired `gatsby-remark-picture` and replaced it with `gatsby-remark-images`. `gatsby-remark-images` is an official Gatsby plugin, and it supports the pathPrefix functionality. In contrast, `gatsby-remark-picture` is not an official plugin, has not a wide adoption (30 downloads this week) and has not received any update over the last 2 years, so I thought it's now a good time for its retirement.

### CODE REVIEW

**Comment by sahilrajput03** [comment]
I tried to run the site locally but couln't, coz of the same reason. I am amazed how testing works coz it won't be feasible unless its deployed to target. :thinking: 
It would be amazing if the works..., @blelem could you please share a version of repo that fix this issue with local hosting , it would be of great help to me.

**Comment by sahilrajput03** [comment]
@blelem , I had no idea if I could clone the repo, and get this latest commit from it. Thanks, I'm just trying to build and run it now. :smiley:

**Comment by blelem** [comment]
@sahilrajput03 , you don't need this fix to run the site locally, the master branch works fine when run locally. Provided that you have[ Gatsby CLI ](https://www.gatsbyjs.com/docs/quick-start/) and npm installed, simply checkout the master then:
  `npm install`
`gatsby serve`
you'll also need a little bit of patience, as building the site the first time takes quite a while.

**Comment by sahilrajput03** [comment]
O thanks, i though i need to install all the dependencies to be able to build and run the site, okag thanks man!!.

**Comment by sahilrajput03** [comment]
> @sahilrajput03 , you don't need this fix to run the site locally, the master branch works fine when run locally. Provided that you have[ Gatsby CLI ](https://www.gatsbyjs.com/docs/quick-start/) and npm installed, simply checkout the master then:
> `npm install`
> `gatsby serve`
> you'll also need a little bit of patience, as building the site the first time takes quite a while.

Are you talking about this official repo or your repo which you have forked from this?

**Comment by sahilrajput03** [comment]
> O thanks, i though i need to install all the dependencies to be able to build and run the site, okag thanks man!!.

You may ignore this message  coz I'm really noob :) :1st_place_medal: .

**Comment by sahilrajput03** [comment]
> > @sahilrajput03 , you don't need this fix to run the site locally, the master branch works fine when run locally. Provided that you have[ Gatsby CLI ](https://www.gatsbyjs.com/docs/quick-start/) and npm installed, simply checkout the master then:
> > `npm install`
> > `gatsby serve`
> > you'll also need a little bit of patience, as building the site the first time takes quite a while.

Are you talking about this official repo (fso's official one )or your repo @blelem/fullstackopen which you have forked from this?

**Comment by sahilrajput03** [comment]
### If i try to do `npm i` in ofiicial fullstackopen repo, and then do `gatsby build` it shows this error to me - 

image

### What am i doing wrong?

**Pull request closed without merging**
