### PR TITLE
Mention that a credit card is required for Fly free account

### PR DESCRIPTION
**Pull request by Vinayaka2k**

### CODE REVIEW

**Comment by nGonium** [comment]
You don't need a credit card for fly.io. When you first sign up, there's a small gray text below the credit card form that says try fly.io for free. Course may want to clarify this since the print is quite small and easy to overlook

**Comment by manundi** [comment]
nGonium did you check that out ? I did find that grey small label and selected try for free but flyctl launch in powershell returns error: 
image
After region select.

**Comment by manundi** [comment]
Also this Fly community post suggests that credit card is needed: https://community.fly.io/t/does-the-free-tier-require-a-credit-card-or-credits-to-be-added-to-the-account/5803

**Comment by manundi** [comment]
@Vinayaka2k

**Pull request closed without merging**
