### PR TITLE
Update part1d.md - missing return() in Button component

### PR DESCRIPTION
**Pull request by inshal-haq**
in part1d, at the end of Conditional rendering, the Button component needs to have return () to render button

p.s. thank you for these valuable lessons fso!

### CODE REVIEW

**Comment by inshal-haq** [comment]
Also can update in "Debugging React applications" section, when Button component is re-shown

**Comment by kahlstrm** [comment]
The syntax in the example is correct, arrow functions do implicit returns with the `() => expression`-syntax, see [Arrow function expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#description).

**Comment by inshal-haq** [comment]
Oh wait, I just noticed this. My mistake, I was using curly braces rather than the parantheses that they are using

Thank you! closing...

**Comment by inshal-haq** [comment]
Incorrect commit, code is working as intended, using implicit return in arrow function

**Pull request closed without merging**
