### PR TITLE
Autofix markdown lint parts 0-7

### PR DESCRIPTION
**Pull request by onzfonz**
This PR is to address some of the rules that are covered in [markdown lint](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md) that I think would be easy fixes though they require larger code changes.  For these changes, I used a [vscode Markdown Lint Plugin](https://github.com/DavidAnson/markdownlint) 

autofix (the changes related to this PR) - are mostly to fix rules around trailing spaces (having spaces at the end of lines that isn't a 0 or 2), putting blank lines around headers and code blocks, and providing syntax languages for code blocks.  I think a couple that I used (like plantuml in 0b) are not supported by gatsby, but wanted to use it anyways as I thought it would be nice to describe (it does throw a warning during gatsby develop, so happy to move out as well)

I also created another pull request #2412 that builds off of this one but makes more opinionated changes

and finally a [controversial branch](https://github.com/onzfonz/comp227/tree/controversial_markdown_lint) where I changed all underscores to asterisks for example and so I thought that is much more subjective.

The markdown lint config file that I used for all three is below:

```json
"markdownlint.config": {
            "default": true,
            "MD003": {
              "style": "atx" //atx is the current style used in the document
            },
            "MD004": {
              "style": "dash" //I use dashes as that is what github defaults to with unordered lists
            },
            "MD007": {
              "indent": 4 //again, completely subjective to use 4 spaces as indentation for unordered sublists
            },
            "MD013": false, //turns off max number of characters on a line and can be configured more
            "MD033": false, //turns off the use of inline HTML
            "MD035": {
                "style": "---" //style to use for horizontal rules
            },
            "MD041": false, //turns off rule about first line in file needing to be a top-level header
            "MD049": { //only followed for controversial branch
                "style":"asterisk"
            },
            "MD050": { //only followed for controversial branch
                "style":"asterisk"
            }
    },
```
The goal would be that if this ends up being followed for the entire project, perhaps a check could be instituted for future markdown changes

### CODE REVIEW

**Comment by mluukkai** [comment]
hmm. this is a pretty scary pr due to the size. would have preferred to have one pr peer part.

could you at least resolve the conflicts?

**Comment by onzfonz** [comment]
Totally understand if you want to wait until your maintenance period for many of the changes or if you are even reluctant to have any of them in, especially the later ones.

I was able to resolve some of the conflicts since this was originally opened, but I'll look at resolving any remaining conflicts this weekend.

**Comment by onzfonz** [comment]
Conflicts are resolved in this and my remaining PRs which again, are not compulsory.
Totally understand if you still don't want to move forward with this until later.
Thanks again!

**Comment by onzfonz** [comment]
closing and opened separate PR's based off of request here

**Pull request closed without merging**
