### PR TITLE
Adds formik `live-debug` to understand available features from formik.

### PR DESCRIPTION
**Pull request by sahilrajput03**
I know adding content would be critical coz it would need finnish and chinese tranlations too.
Thanks.

### CODE REVIEW

**Comment by sahilrajput03** [comment]
image
Above is latest screenshot changed content.

**Comment by sahilrajput03** [comment]
image
This is latest diff screenshot.

**Comment by sahilrajput03** [comment]
Additionally, https://codesandbox.io/s/proposed-debuggin-area-fso-s8k1f?file=/src/index.js
this is live demo of the working of the debuggin area as its proposed by this PR.
Thanks!

**Comment by Kaltsoon** [comment]
Wouldn't a simple `console.log` provide a cleaner output? Adding debug messages to the UI isn't really the best debugging practice

**Comment by sahilrajput03** [comment]
Okay. Its all good then. :)

**Pull request closed without merging**
