### PR TITLE
fix problem with generated HTML

### PR DESCRIPTION
**Pull request by dragancajic**
Markdown seems to be **good**, BUT generated _HTML_ from Markdown is _NOT_ ! :thinking:

Screenshot at 2023-01-20 01:15:18
Screenshot at 2023-01-20 01:17:29
Screenshot at 2023-01-20 01:17:33
Screenshot at 2023-01-20 01:18:04

### CODE REVIEW

**Review by akirataguchi115 — CHANGES_REQUESTED** [review]
Why is there a mailto mluukkai%40iki.fi? Also could you be a bit more specific on what is wrong with the HTML and maybe remove some unnecessary picture from this PR?

**Comment by akirataguchi115** [comment]
and now there's only an image left in the changes?

**Comment by dragancajic** [comment]
I will remove it! We don't need it, BUT this is the rendered HTML, ... it has the problem:

``` html
<p>It is an <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST">HTTP POST</a> request to the server address <i>new<em>note</em></i>. The server responds with HTTP status code 302. This is a [URL redirect](<a href="https://en.wikipedia.org/wiki/URL">https://en.wikipedia.org/wiki/URL</a>redirection), with ...
```

**Comment by dragancajic** [comment]
> mluukkai%40iki.fi

Sorry, it's my fault!

**Comment by akirataguchi115** [comment]
What is the problem?

**Comment by dragancajic** [comment]
So, let's see what we have in the user agent/browser:

Screenshot from 2023-01-20 15-17-49
Screenshot from 2023-01-20 15-18-04
Screenshot from 2023-01-20 15-19-40

Now, I have switch back to work on Fedora Linux Workstation 35, ...

**Comment by akirataguchi115** [comment]
Can you describe your problem without using so many images? I have no idea what the images are meant to represent.

**Comment by dragancajic** [comment]
The problem is with broken text and link, it should say something like this:
``` html
It is an [HTTP POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) request to the server address <em>new_note</em>. The server responds with HTTP status code 302. This is a [URL redirect](https://en.wikipedia.org/wiki/URL_redirection), with ...
```

link should point to:
https://en.wikipedia.org/wiki/URL_redirection

and POST request was sent to address 'new_note', and redirection happens, as text said:

"... with which the server asks the browser to do a new HTTP GET request to the address defined in the header's Location - the address notes."

**Comment by dragancajic** [comment]
> Can you describe your problem without using so many images? I have no idea what the images are meant to represent.

in images there can be seen incorrect HTML code that is send to browser, ...

new_note should be only in _italic_, not the rest of the text, and URL_redirect should be link, not just URL,

we don't need this link -> https://en.wikipedia.org/wiki/URL

**Comment by akirataguchi115** [comment]
Now I get the issue! Instead of pointing to https://en.wikipedia.org/wiki/URL the url should point to https://en.wikipedia.org/wiki/URL_redirection. Could you change the code so that it would point to the correct wikipedia article?

Good catch!👍

**Comment by dragancajic** [comment]
Thank God, ... if I made myself clear! Huh, that was tough stuff! :smile:

**Comment by dragancajic** [comment]
> Now I get the issue! Instead of pointing to https://en.wikipedia.org/wiki/URL the url should point to https://en.wikipedia.org/wiki/URL_redirection. Could you change the code so that it would point to the correct wikipedia article?
> 
> Good catch!+1

That's the main problem, Markdown is good, but HTML is not, .... Markdown GitHub engine is maybe in question, ... but

I have found some changes that may or may not have impact on this problem!

Professor Matti Luukkainen (https://github.com/mluukkai) changed code base, ... I have found one backslash (escape sequence character) in "new_note" ... it was like this "new\_note":

<i>new\_note</i>

screenshot(s):

Screenshot from 2023-01-20 16-17-29
Screenshot from 2023-01-20 17-21-40

**Comment by dragancajic** [comment]
Maybe to use insted of <i>i</i> to use <em>em</em> tag, that's the better practice for emphasizing, OR to stick together with Markdown notation -> *italic* (\*italic\*) , or _italic_ (\_italic\_), ...

I have tried to make Google search on that topic -> Markdown engine that is used by GitHub:

https://www.google.com/search?q=github+markdown+engine

**Comment by dragancajic** [comment]
This is good **reading** from _GitHub Docs_. I thing it will be useful:

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Screenshot from 2023-01-20 18-03-24

**Comment by dragancajic** [comment]
~ Setting a Markdown processor for your GitHub Pages site using Jekyll
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll

**Comment by dragancajic** [comment]
~ ***R e f e r e n c e s***
- [markdown-it demo](https://markdown-it.github.io/)
- [Forms and HTTP POST | Fundamentals of Web apps](https://fullstackopen.com/en/part0/fundamentals_of_web_apps#forms-and-http-post)
- [dragancajic/fullstack-hy2020.github.io](https://github.com/dragancajic/fullstack-hy2020.github.io)
- [_Learn PISIO_](https://learn-pisio.eu5.org/about.php)

### _"Knowledge Against Poverty!!!"_
___
_"The Learning Process"_<br />
> Yeah man
Before success can manifest
You got to go through the learning process
Come... learn...

[_Scooter_](https://www.youtube.com/watch?v=4vKYXVfvIO4)
___
Screenshot from 2023-01-20 20-53-13

**Review by akirataguchi115 — APPROVED** [review]
image
LGTM!

**Comment by dragancajic** [comment]
It's looking NICE! :books: :book:

Anybody else is going to review the _Pull Request_ (PR), professor [_Matti Luukkainen_](https://fullstackopen.com/en/part0/general_info#interview-promise) --> @mluukkai maybe, or not? :thinking:
OK! Let's Get This Merged (LGTM)! Who is gonna _merge_ the pull request?

''Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.''

- ### _Full stack open_
Despite the repo name this IS the current course repository
https://github.com/fullstack-hy2020/fullstack-hy2020.github.io

So, THIS is the original repository of the _Full Stack Open_ course.

I have my own _**fork**_ [dragancajic/fullstack-hy2020.github.io](https://github.com/dragancajic/fullstack-hy2020.github.io) and I'll sync my fork with the upstream, :grin:
WHEN the pull request has been merged! I think :thinking: that's the way how things work with pull requests! :wink:

**Comment by dragancajic** [comment]
> This is going to get merged when the owners* see this so let's not expect anything too quick to happen smile You've done your part; good job & thank you heartpulse

Thank you, [Akira Taguchi](https://github.com/akirataguchi115), for your help and cooperation! :+1:
It's nice to have community out there on which one can rely on.  :hugs: :handshake:

Have a nice weekend and to the next _Pull Request_ (PR),

_Cheers!_ :wine_glass: :beers: :clinking_glasses: and take care of yourself,
Драган Ћајић / _Dragan Cajic_

**Pull request merged**
