### PR TITLE
Update part10a.md

### LINKED ISSUE #733: Part 10a: expo command not found [windows]
After globally installing expo-cli with `npm install --global expo-cli`,
running `expo init rate-repository-app` leads to error:
> 'expo' is not recognized as an internal or external command,
> operable program or batch file.

For me this was the first time installing anything globally and the directory C:\Users\<USER>\AppData\Roaming\npm was not included in the Environmental variables. Adding the directory to path fixed the issue. Other operating system users _might_ experience a similar issue.

Consider adding a disclaimer regarding the topic.

### PR DESCRIPTION
**Pull request by tveijola**
Closes #733

### CODE REVIEW

**Comment by Kaltsoon** [comment]
If the global installation doesn't work, maybe it would be better to instruct people to use `npx expo-cli init`. This however requires changes in the `package.json` scripts, e.g. `expo start` needs to be changed into `npx expo-cli start` and so on.

**Comment by tveijola** [comment]
Thanks for the comment. The issue was not the installation itself, but the global root directory not being included in the system path.

**Comment by Kaltsoon** [comment]
That's true. I was thinking what's the easiest way to execute the command if you can't run it globally. I'm afraid most of the people have no idea what "the npm root directory must be added to the system path"  means.

**Comment by tveijola** [comment]
Oh yes, I didn't think of that. Is it possible to install expo locally in the project directory? The command could then be run only from the project directory. Would that cause more issues than solve?

**Comment by sahilrajput03** [comment]
> Oh yes, I didn't think of that. Is it possible to install expo locally in the project directory? The command could then be run only from the project directory. Would that cause more issues than solve?

Installing expo globally is just better!

**Pull request closed without merging**
