### PR TITLE
Added CodeSandBox : a free IDE & Hosting plateform

### PR DESCRIPTION
**Pull request by Monsef-Noubadji**
I Added CodeSandBox : a free IDE & Hosting plateform for nodejs applications that works well with either React , Angular or Vue js.

### CODE REVIEW

**Comment by mluukkai** [comment]
does codesandbox really support production quality hosting of apps, and does it allow deploying a backend? from documentations this is not obvious

**Comment by Monsef-Noubadji** [comment]
Yes sir it does, it is supporting backend since 2019 to build full stack applications and deploy them as well on Netlify on Vercel.

**Comment by mluukkai** [comment]
ok, I'll add it but in another commit. I formulate the text a bit. Thanks!

**Comment by Monsef-Noubadji** [comment]
My pleasure, thank you for taking time to review this !

**Pull request closed without merging**
