### PR TITLE
propose: use body parser in Exercise 4.2 step 2 

### PR DESCRIPTION
**Pull request by Shivam-Chahar**
Without the use of a body parser in Exercise 4.2 step 2, incoming JSON object from the post request made with the postman, the whole object body is not getting saved in MongoDB collection. Only the _id produced by MongoDB is getting saved. Using a body-parser will solve this problem

### CODE REVIEW

**Comment by Kaltsoon** [comment]
Is this necessary because body-parser middleware is already used in exercise 4.1?

**Comment by Shivam-Chahar** [comment]
It is just necessary to tell which to use and where otherwise beginners will find difficulty in knowing what's happening and why

**Comment by Kaltsoon** [comment]
What do you mean by "which to use"? Doesn't course only use the `express.json` body parser?

**Comment by Shivam-Chahar** [comment]
Nowhere it is mentioned before Exercise 4.2 to use express.json body-parser or even about the body-parser

**Comment by Kaltsoon** [comment]
This is from part 3a:
Screenshot 2020-07-31 at 11 11 10

In addition, as I mentioned exercise 4.1 uses the `express.json` body parser.

**Comment by Shivam-Chahar** [comment]
You are right, But when Express 4.0 was released bundled middleware was removed from Express and made them separate packages instead. The syntax then changed from app.use(express.json()) to app.use(bodyParser.json()) after installing the bodyParser module.

**Comment by Kaltsoon** [comment]
As far as I know, express (>=4.16.0) doesn't encourage to use the `body-parser` package anymore and use `express.json` instead. I think we should follow this guideline and not introduce the `body-parser` package. Supporting older express versions doesn't make sense.

**Comment by Shivam-Chahar** [comment]
okay

**Pull request closed without merging**
