### PR TITLE
Added Replit - free hosting plateform and IDE

### PR DESCRIPTION
**Pull request by Monsef-Noubadji**
Beside Fly.io, i added **replit.com** as a good IDE and hosting services with predefined domain through an HTTPS Connection

### CODE REVIEW

**Comment by Monsef-Noubadji** [comment]
hello sir ,thank you for taking time to go through my request , i do use replit to host my code , here's an example : [https://mawthouq-beta.monsef-noubadji.repl.co/](https://mawthouq-beta.monsef-noubadji.repl.co/)

**Comment by mluukkai** [comment]
content added in another commit

**Comment by mluukkai** [comment]
Can you host a node backend there, and is it possible to define env
variables for the apps? If, then you may add this to the below
sentence that mentions Render

ke 21. syysk. 2022 klo 14.42 Monsef Noubadji ***@***.***)
kirjoitti:

**Comment by Monsef-Noubadji** [comment]
ke 21. syysk. 2022 klo 14.42 Monsef Noubadji ***@***.***)
kirjoitti:
yes sir, the nodejs backend of some of my apps is hosted there, and you get the option to choose a Nodejs template to start with once you create a new project, and yes as well , you can define env variables using the "Secrets tab" marked with a🔒, here's an example : 
Screenshot 2022-10-11 13 26 39

**Comment by mluukkai** [comment]
thanks!

**Comment by Monsef-Noubadji** [comment]
My pleasure sir.

**Pull request closed without merging**
